spring:
  application:
    name: volunteer-app.asesordigital

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /swagger.v1+json
  api:
    title: VOLUNTEER APP BACKEND API
    description: Servicios REST para la aplicación de voluntariado
    version: 1.0

social:
  googleClientId: ${GOOGLE_CLIENT_ID}
  googleClientSecret: ${GOOGLE_CLIENT_SECRET}

server:
  port: 8085
  servlet:
    context-path: /api/v1/back-volunteer-app
  forward-headers-strategy: native
  tomcat:
    max-file-size: 10MB
    max-request-size: 10MB
    max-http-form-post-size: 10485760

request-mapping:
  controller:
    authentication: authentications
    role: roles
    user: users
    volunteer: volunteers
    organization: organizations
    activity: activities
    mission: missions
    volunteer-group: volunteer-groups
    volunteer-dashboard: volunteers-dashboard
    organization-dashboard: organizations-dashboard
    super-admin-dashboard: super-admins-dashboard
    activity-coordinator: activity-coordinators
    location: locations
    datashare-volunteer-organization: datashare-volunteers-organizations
    volunteer-organization: volunteers-organizations
    postulation: postulations
    attendace: attendances
    review: reviews
    notification: notifications
